add comments
Kylehinks97/fe-nc-news-project pull request #5
Opened 2023-05-31 11:31 UTC by Kylehinks97

2023-05-31 14:23 UTC, HannahBurks requested changes
Nice work Kyle, just would like to see some handling added for if there are no comments on an article yet. I would also say your 'loading' message is very small and on desktop view and a lot of the content is going to the left of the screen. Don't worry about CSS too much yet but I would try to make things more centered and easy to read.

2023-05-31 14:23 UTC, HannahBurks commented on fe-nc-news-project/src/Comments.jsx
> +        console.log(comments);
Lets remove the stray console log here :)

2023-05-31 14:23 UTC, HannahBurks commented on fe-nc-news-project/src/Comments.jsx
> +  {comments.map((comment) => {
We also want to add something, so that if there are no comments on an article yet, we display a message such as 'no comments yet'

2023-06-01 08:05 UTC, aloush-dev approved these changes
Nice thanks for making the changes.

Merge away.

2023-06-01 08:07 UTC, merged