add ability to vote on an article-task7
Kylehinks97/fe-nc-news-project pull request #6
Opened 2023-06-01 11:19 UTC by Kylehinks97

2023-06-01 12:52 UTC, HannahBurks requested changes
Nice work Kyle, but a few changes ie loading state and also changing where our .catch() are :)

2023-06-01 12:52 UTC, HannahBurks commented on fe-nc-news-project/src/Comments.jsx
>    const [comments, setComments] = useState([]);
We also want to have a loading state for our comments

2023-06-01 12:52 UTC, HannahBurks commented on fe-nc-news-project/src/utils.js
>          console.log(err, "request error");
We don't need .catch in our api file. We want to add a .catch when we invoke the util function in the components.

2023-06-01 12:52 UTC, HannahBurks commented on fe-nc-news-project/src/utils.js
> +    }).catch((err) => {
Make sure to remove any .catch on this file

2023-06-01 12:54 UTC, HannahBurks commented
I've also just tried the voting feature and on page refresh it doesn't work. Think about why this may be

2023-06-02 08:24 UTC, itsaliabdallah commented on fe-nc-news-project/src/utils.js
> +    console.log(result.data.article.votes, "<-- in the util");
remove please

2023-06-02 08:26 UTC, aloush-dev approved these changes
nice work.
feel free to merge

2023-06-02 08:27 UTC, merged